### ISSUE TITLE
Graphos format

### ISSUE THREAD

**Issue by jcmartins** [lukasmartinelli/pgclimb#1]
Please export to RDF [https://en.wikipedia.org/wiki/Resource_Description_Framework](url)

**Comment by lukasmartinelli** [comment]
Can one create RDF representation of a query result without any additional meta data?

You can create custom XML formats by using the templating feature.
https://github.com/lukasmartinelli/pgclimb#templates

**Comment by lukasmartinelli** [comment]
> You can create custom XML formats by using the templating feature.
> https://github.com/lukasmartinelli/pgclimb#templates
